"use client";

import { useEffect, useId, useRef, useState, type FormEvent } from "react";
import { Camera, CheckCircle2, ImageUp, Keyboard, RotateCcw, X } from "lucide-react";
import { errorMessage, participationsApi } from "@/lib/api";
import type { CheckinResponse } from "@/types";

type ScannerInstance = import("html5-qrcode").Html5Qrcode;

type QrScannerModalProps = {
  open: boolean;
  eventId: string;
  eventTitle: string;
  onClose: () => void;
  onCheckedIn?: (result: CheckinResponse) => void | Promise<void>;
};

function extractQrToken(rawValue: string) {
  const value = rawValue.trim();
  if (!value) return "";

  try {
    const parsed = JSON.parse(value) as Record<string, unknown>;
    for (const key of ["qrToken", "encryptedPayload", "token"]) {
      if (typeof parsed[key] === "string" && parsed[key]) return parsed[key] as string;
    }
  } catch {
    // The QR generated by Ween normally contains the encrypted token directly.
  }

  try {
    const url = new URL(value);
    return url.searchParams.get("qrToken") || url.searchParams.get("token") || value;
  } catch {
    return value;
  }
}

export function QrScannerModal({ open, eventId, eventTitle, onClose, onCheckedIn }: QrScannerModalProps) {
  const reactId = useId();
  const readerId = `qr-reader-${reactId.replace(/[^a-zA-Z0-9_-]/g, "")}`;
  const scannerRef = useRef<ScannerInstance | null>(null);
  const processingRef = useRef(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [session, setSession] = useState(0);
  const [status, setStatus] = useState<"starting" | "scanning" | "submitting" | "success" | "error">("starting");
  const [message, setMessage] = useState("");
  const [result, setResult] = useState<CheckinResponse | null>(null);
  const [manualToken, setManualToken] = useState("");
  const [showManual, setShowManual] = useState(false);

  async function stopScanner() {
    const scanner = scannerRef.current;
    scannerRef.current = null;
    if (!scanner) return;
    try {
      if (scanner.isScanning) await scanner.stop();
      scanner.clear();
    } catch {
      // The camera may already have been released by the browser.
    }
  }

  async function submitToken(rawValue: string) {
    if (processingRef.current) return;
    const qrToken = extractQrToken(rawValue);
    if (!qrToken) {
      setStatus("error");
      setMessage("QR token is empty. Please scan or enter a valid code.");
      return;
    }

    processingRef.current = true;
    setStatus("submitting");
    setMessage("");
    await stopScanner();

    try {
      const checkin = await participationsApi.checkin({ eventId, qrToken });
      setResult(checkin);
      setStatus("success");
      setManualToken("");
      await onCheckedIn?.(checkin);
    } catch (cause) {
      setStatus("error");
      setMessage(errorMessage(cause));
    } finally {
      processingRef.current = false;
    }
  }

  useEffect(() => {
    if (!open) return;
    let cancelled = false;

    processingRef.current = false;
    setStatus("starting");
    setMessage("");
    setResult(null);

    async function startCamera() {
      try {
        const { Html5Qrcode } = await import("html5-qrcode");
        if (cancelled) return;
        const scanner = new Html5Qrcode(readerId, { verbose: false });
        scannerRef.current = scanner;
        await scanner.start(
          { facingMode: "environment" },
          { fps: 10, qrbox: (width, height) => {
            const size = Math.floor(Math.min(width, height) * 0.72);
            return { width: size, height: size };
          } },
          (decodedText) => void submitToken(decodedText),
          () => undefined,
        );
        if (!cancelled) setStatus("scanning");
      } catch (cause) {
        if (cancelled) return;
        setStatus("error");
        const name = cause instanceof Error ? cause.name : "";
        setMessage(
          name === "NotAllowedError"
            ? "Camera permission was denied. Allow camera access or upload a QR image."
            : "The camera could not be opened. Check permission, use HTTPS, or upload a QR image.",
        );
      }
    }

    void startCamera();
    return () => {
      cancelled = true;
      void stopScanner();
    };
    // A new session intentionally creates a fresh camera instance.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, eventId, readerId, session]);

  useEffect(() => {
    if (!open) return;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.key === "Escape") onClose();
    };
    window.addEventListener("keydown", onKeyDown);
    return () => {
      document.body.style.overflow = previousOverflow;
      window.removeEventListener("keydown", onKeyDown);
    };
  }, [onClose, open]);

  async function scanFile(file?: File) {
    if (!file) return;
    processingRef.current = true;
    setStatus("submitting");
    setMessage("");
    try {
      await stopScanner();
      const { Html5Qrcode } = await import("html5-qrcode");
      const fileScanner = new Html5Qrcode(readerId, { verbose: false });
      scannerRef.current = fileScanner;
      const decodedText = await fileScanner.scanFile(file, true);
      processingRef.current = false;
      await submitToken(decodedText);
    } catch {
      processingRef.current = false;
      setStatus("error");
      setMessage("No readable QR code was found in this image. Try a clearer image.");
    } finally {
      if (fileInputRef.current) fileInputRef.current.value = "";
    }
  }

  function retry() {
    processingRef.current = false;
    setShowManual(false);
    setMessage("");
    setResult(null);
    setSession((value) => value + 1);
  }

  function handleManualSubmit(event: FormEvent) {
    event.preventDefault();
    void submitToken(manualToken);
  }

  if (!open) return null;

  return (
    <div className="fixed inset-0 z-[120] flex items-end justify-center bg-slate-950/75 sm:items-center sm:p-5" role="dialog" aria-modal="true" aria-labelledby={`${readerId}-title`}>
      <div className="max-h-[100dvh] w-full overflow-y-auto rounded-t-3xl bg-white shadow-2xl sm:max-w-lg sm:rounded-3xl">
        <div className="sticky top-0 z-10 flex items-start justify-between gap-4 border-b border-slate-100 bg-white/95 px-4 py-4 backdrop-blur sm:px-6">
          <div className="min-w-0">
            <p className="text-xs font-black uppercase tracking-[.18em] text-emerald-600">Volunteer check-in</p>
            <h2 id={`${readerId}-title`} className="mt-1 truncate text-lg font-black text-slate-950">{eventTitle}</h2>
          </div>
          <button type="button" onClick={onClose} aria-label="Close QR scanner" className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-slate-100 text-slate-700 transition hover:bg-slate-200">
            <X className="h-5 w-5" />
          </button>
        </div>

        <div className="p-4 sm:p-6">
          {status === "success" && result ? (
            <div className="py-5 text-center" aria-live="polite">
              {result.participantPhoto ? (
                <img src={result.participantPhoto} alt="" className="mx-auto h-24 w-24 rounded-full object-cover ring-4 ring-emerald-100" />
              ) : (
                <span className="mx-auto grid h-24 w-24 place-items-center rounded-full bg-emerald-50 text-emerald-600"><CheckCircle2 className="h-12 w-12" /></span>
              )}
              <CheckCircle2 className="mx-auto mt-5 h-8 w-8 text-emerald-600" />
              <h3 className="mt-2 text-2xl font-black text-slate-950">Check-in successful</h3>
              <p className="mt-2 text-base font-bold text-slate-700">{result.participantName}</p>
              <p className="mt-1 text-sm text-slate-500">{result.message}</p>
              <div className="mt-6 grid gap-2 sm:grid-cols-2">
                <button type="button" onClick={retry} className="h-12 rounded-xl bg-emerald-600 px-5 text-sm font-bold text-white hover:bg-emerald-700">Scan next participant</button>
                <button type="button" onClick={onClose} className="h-12 rounded-xl border border-slate-200 px-5 text-sm font-bold text-slate-700 hover:bg-slate-50">Finish</button>
              </div>
            </div>
          ) : (
            <>
              <div className="relative aspect-square w-full overflow-hidden rounded-2xl bg-slate-950">
                <div id={readerId} className="h-full w-full [&_video]:h-full [&_video]:w-full [&_video]:object-cover" />
                {(status === "starting" || status === "submitting") && (
                  <div className="absolute inset-0 grid place-items-center bg-slate-950/80 text-center text-white">
                    <div><span className="mx-auto block h-9 w-9 animate-spin rounded-full border-2 border-emerald-400 border-t-transparent" /><p className="mt-3 text-sm font-bold">{status === "submitting" ? "Checking participant…" : "Opening camera…"}</p></div>
                  </div>
                )}
              </div>

              <p className="mt-4 text-center text-sm leading-6 text-slate-500">Place the participant&apos;s QR code inside the frame. It will be read automatically.</p>

              {status === "error" && (
                <div className="mt-4 rounded-xl border border-red-200 bg-red-50 p-3 text-sm font-semibold text-red-700" role="alert">{message}</div>
              )}

              <div className="mt-4 grid grid-cols-2 gap-2">
                <button type="button" onClick={() => fileInputRef.current?.click()} disabled={status === "submitting"} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 text-xs font-bold text-slate-700 hover:bg-slate-50 disabled:opacity-50">
                  <ImageUp className="h-4 w-4" /> Upload QR image
                </button>
                <button type="button" onClick={() => setShowManual((value) => !value)} disabled={status === "submitting"} className="inline-flex h-11 items-center justify-center gap-2 rounded-xl border border-slate-200 px-3 text-xs font-bold text-slate-700 hover:bg-slate-50 disabled:opacity-50">
                  <Keyboard className="h-4 w-4" /> Enter token
                </button>
                <input ref={fileInputRef} type="file" accept="image/*" className="hidden" onChange={(event) => void scanFile(event.target.files?.[0])} />
              </div>

              {showManual && (
                <form onSubmit={handleManualSubmit} className="mt-3 flex flex-col gap-2 sm:flex-row">
                  <input value={manualToken} onChange={(event) => setManualToken(event.target.value)} autoComplete="off" placeholder="Paste QR token" aria-label="QR token" className="h-11 min-w-0 flex-1 rounded-xl border border-slate-200 px-3 text-sm outline-none focus:border-emerald-500" />
                  <button type="submit" disabled={!manualToken.trim() || status === "submitting"} className="h-11 rounded-xl bg-slate-900 px-5 text-sm font-bold text-white disabled:opacity-50">Check in</button>
                </form>
              )}

              {status === "error" && (
                <button type="button" onClick={retry} className="mt-3 inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl bg-emerald-600 text-sm font-bold text-white hover:bg-emerald-700">
                  <RotateCcw className="h-4 w-4" /> Try camera again
                </button>
              )}

              <div className="mt-4 flex items-start gap-2 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-slate-500">
                <Camera className="mt-0.5 h-4 w-4 shrink-0" /> Camera access requires permission and a secure HTTPS connection on phones.
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
